# Generated by Django 4.0.4 on 2022-05-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='description',
        ),
    ]
