# Generated by Django 4.0.4 on 2022-05-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
