# Generated by Django 4.0.4 on 2022-05-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0002_rename_name_habit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
