# Generated by Django 4.0.4 on 2022-05-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0003_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='time',
        ),
    ]
