# Generated by Django 4.0.4 on 2022-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0003_habit_user_tagname_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tagname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='habit',
            name='task',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='units',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
