# Generated by Django 4.0.4 on 2022-05-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0004_rename_date_record_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
    ]
