# Generated by Django 4.0.4 on 2022-05-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0006_remove_record_habit_remove_habit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='Habits.habit'),
        ),
    ]
