# Generated by Django 4.0.4 on 2022-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0008_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(blank=True),
        ),
    ]
