# Generated by Django 4.0.4 on 2022-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habits', '0009_alter_habit_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
